name: Get Latest Version And Publish

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test some Packages
      run: |
        cd mysql-python
        choco pack
        choco install --no-progress mysql-python -source "'.;https://chocolatey.org/api/v2/'"
        choco uninstall -y mysql-python
        cd ../
        cd love.install
        choco pack
        choco install --no-progress love.install -source "'.;https://chocolatey.org/api/v2/'"
        Test-Path -Path "C:\Program Files\LOVE"
        choco uninstall -y love.install
        Test-Path -Path "C:\Program Files\LOVE"
        cd ../
        cd travis
        choco pack
        choco install --no-progress travis -source "'.;https://chocolatey.org/api/v2/'"
        choco uninstall travis
        cd ../
        cd love.portable
        choco pack
        choco install --no-progress love.portable -source "'.;https://chocolatey.org/api/v2/'"
        choco uninstall -y love.portable
        cd ../

    # Runs a set of commands using the runners shell
    - uses: actions/upload-artifact@v2
      with:
        name: chocologs
        path: C:\ProgramData\chocolatey\logs\chocolatey.log
  test-manim-latex:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
    - name: Install Manim
      run: |
        choco install --no-progress manim
        cd "manim-latex"
        choco pack
        choco install --no-progress manim-latex -source "'.;https://chocolatey.org/api/v2/'"
        cd ../
        $env:PATH="C:\tools\TinyTeX\bin\win32;$env:PATH"
        echo "::set-env name=PATH::$($env:PATH)"
    - name: Install Manim and Manim-Tex and test
      run: |
        curl -L https://pastebin.com/raw/QcbYFiTz -o tex.py
        pip install https://github.com/ManimCommunity/manim/archive/master.zip
        manim tex.py
        choco uninstall manim-latex
    - uses: actions/upload-artifact@v2
      with:
        name: chocologs
        path: C:\ProgramData\chocolatey\logs\chocolatey.log
    - uses: actions/upload-artifact@v2
      with:
        name: mediaManim.zip
        path: media